const agents = [
  {
    id: "a1",
    name: "Sophia Marlowe",
    title: "Senior Property Consultant",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    phone: "+1 (555) 201-4532",
    email: "sophia@luxestate.com",
    location: "Manhattan, New York",
    bio: "With 12 years of luxury real estate experience, Sophia specialises in Manhattan penthouses and waterfront properties. She has closed over $480M in transactions and consistently ranks among the top 1% of agents nationwide.",
    specialties: ["Luxury Condos", "Penthouses", "Investment Properties"],
    languages: ["English", "French", "Spanish"],
    rating: 4.9,
    reviewCount: 214,
    propertiesSold: 312,
    yearsExp: 12,
    propertiesActive: 8,
    social: { instagram: "#", linkedin: "#", twitter: "#" },
    certifications: ["Certified Luxury Home Marketing Specialist", "Accredited Buyer's Representative"],
    status: "Active",
  },
  {
    id: "a2",
    name: "Marcus Chen",
    title: "Commercial Property Expert",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    phone: "+1 (555) 308-7741",
    email: "marcus@luxestate.com",
    location: "Beverly Hills, California",
    bio: "Marcus brings a strategic investment perspective to every deal. Specialising in commercial real estate and high-value residential portfolio management across the West Coast.",
    specialties: ["Commercial", "Investment", "Multi-Family"],
    languages: ["English", "Mandarin"],
    rating: 4.8,
    reviewCount: 178,
    propertiesSold: 264,
    yearsExp: 9,
    propertiesActive: 11,
    social: { instagram: "#", linkedin: "#", twitter: "#" },
    certifications: ["Certified Commercial Investment Member", "LEED AP"],
    status: "Active",
  },
  {
    id: "a3",
    name: "Isabelle Fontaine",
    title: "Residential Sales Specialist",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    phone: "+1 (555) 419-0032",
    email: "isabelle@luxestate.com",
    location: "Miami Beach, Florida",
    bio: "Isabelle's passion for architecture and interior design gives her clients a unique edge. Her deep knowledge of Miami's luxury market and waterfront properties makes her a sought-after advisor.",
    specialties: ["Waterfront", "Luxury Villas", "New Developments"],
    languages: ["English", "French", "Portuguese"],
    rating: 4.9,
    reviewCount: 193,
    propertiesSold: 287,
    yearsExp: 10,
    propertiesActive: 7,
    social: { instagram: "#", linkedin: "#", twitter: "#" },
    certifications: ["Certified Luxury Home Marketing Specialist", "Real Estate Negotiation Expert"],
    status: "Active",
  },
  {
    id: "a4",
    name: "James Harrington",
    title: "Estate & Land Specialist",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    phone: "+1 (555) 512-8890",
    email: "james@luxestate.com",
    location: "Greenwich, Connecticut",
    bio: "James has an unrivalled track record in estate and land sales across New England. His clients include Fortune 500 executives, diplomats, and institutional investors.",
    specialties: ["Estates", "Land", "Historic Properties"],
    languages: ["English"],
    rating: 4.7,
    reviewCount: 141,
    propertiesSold: 198,
    yearsExp: 15,
    propertiesActive: 5,
    social: { instagram: "#", linkedin: "#", twitter: "#" },
    certifications: ["Graduate REALTOR Institute", "Certified Residential Specialist"],
    status: "Active",
  },
];

const properties = [
  {
    id: "p1",
    title: "The Glass Penthouse",
    address: "432 Park Avenue, New York, NY 10022",
    city: "New York",
    state: "NY",
    zip: "10022",
    type: "Penthouse",
    status: "For Sale",
    price: 12500000,
    priceLabel: "$12,500,000",
    size: 6200,
    bedrooms: 5,
    bathrooms: 6,
    garage: 2,
    yearBuilt: 2021,
    lat: 40.7614,
    lng: -73.9776,
    agentId: "a1",
    featured: true,
    tags: ["Featured", "New"],
    description: "An extraordinary full-floor penthouse atop one of Manhattan's most prestigious towers. Floor-to-ceiling glass walls offer panoramic views of Central Park and the Manhattan skyline.",
    amenities: ["Rooftop Terrace", "Home Theater", "Wine Cellar", "Concierge", "Gym", "Pool", "Smart Home", "Private Elevator"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    ],
    floorPlan: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800",
    views: 4821,
    saves: 312,
    daysListed: 14,
    pendingApproval: false,
  },
  {
    id: "p2",
    title: "Malibu Oceanfront Villa",
    address: "28420 Pacific Coast Hwy, Malibu, CA 90265",
    city: "Malibu",
    state: "CA",
    zip: "90265",
    type: "Villa",
    status: "For Sale",
    price: 22000000,
    priceLabel: "$22,000,000",
    size: 8400,
    bedrooms: 7,
    bathrooms: 9,
    garage: 4,
    yearBuilt: 2019,
    lat: 34.0259,
    lng: -118.7798,
    agentId: "a3",
    featured: true,
    tags: ["Featured", "Luxury"],
    description: "Direct oceanfront compound on one of the most coveted stretches of Malibu coastline.",
    amenities: ["Private Beach", "Infinity Pool", "Home Theater", "Guest House", "Gym", "Spa", "Chef's Kitchen", "6-Car Garage"],
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800",
    ],
    floorPlan: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    views: 9234,
    saves: 541,
    daysListed: 7,
    pendingApproval: false,
  },
  {
    id: "p3",
    title: "Brooklyn Heights Brownstone",
    address: "144 Remsen Street, Brooklyn, NY 11201",
    city: "Brooklyn",
    state: "NY",
    zip: "11201",
    type: "Townhouse",
    status: "For Sale",
    price: 4200000,
    priceLabel: "$4,200,000",
    size: 3800,
    bedrooms: 4,
    bathrooms: 3,
    garage: 1,
    yearBuilt: 1898,
    lat: 40.6958,
    lng: -73.9955,
    agentId: "a1",
    featured: false,
    tags: ["Historic"],
    description: "A meticulously restored pre-war brownstone in the heart of Brooklyn Heights.",
    amenities: ["Garden", "Fireplace", "Roof Deck", "Wine Cellar", "Original Details"],
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
    ],
    floorPlan: null,
    views: 2341,
    saves: 198,
    daysListed: 32,
    pendingApproval: false,
  },
  {
    id: "p4",
    title: "Miami Beach Art Deco Mansion",
    address: "1901 Collins Avenue, Miami Beach, FL 33139",
    city: "Miami Beach",
    state: "FL",
    zip: "33139",
    type: "Mansion",
    status: "For Sale",
    price: 18750000,
    priceLabel: "$18,750,000",
    size: 11200,
    bedrooms: 8,
    bathrooms: 10,
    garage: 3,
    yearBuilt: 2022,
    lat: 25.7816,
    lng: -80.1303,
    agentId: "a3",
    featured: true,
    tags: ["Featured", "Luxury", "New"],
    description: "A breathtaking Art Deco-inspired estate steps from Miami Beach shoreline.",
    amenities: ["Ocean Views", "Lagoon Pool", "Private Gym", "Home Theater", "Chef's Kitchen", "Smart Home", "Guest Suite", "Cabana"],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=800",
    ],
    floorPlan: null,
    views: 6712,
    saves: 423,
    daysListed: 5,
    pendingApproval: false,
  },
  {
    id: "p5",
    title: "Pacific Heights Victorian",
    address: "2640 Steiner Street, San Francisco, CA 94115",
    city: "San Francisco",
    state: "CA",
    zip: "94115",
    type: "House",
    status: "For Rent",
    price: 28000,
    priceLabel: "$28,000/mo",
    size: 5100,
    bedrooms: 5,
    bathrooms: 4,
    garage: 2,
    yearBuilt: 1905,
    lat: 37.7924,
    lng: -122.4349,
    agentId: "a2",
    featured: false,
    tags: ["Historic", "Rental"],
    description: "An immaculate Victorian masterpiece perched atop Pacific Heights.",
    amenities: ["Bay Views", "Garden", "Deck", "Fireplace", "Chef's Kitchen"],
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800",
    ],
    floorPlan: null,
    views: 1890,
    saves: 142,
    daysListed: 18,
    pendingApproval: false,
  },
  {
    id: "p6",
    title: "Aspen Mountain Chalet",
    address: "505 Gold Run Road, Aspen, CO 81611",
    city: "Aspen",
    state: "CO",
    zip: "81611",
    type: "Chalet",
    status: "For Sale",
    price: 9800000,
    priceLabel: "$9,800,000",
    size: 7200,
    bedrooms: 6,
    bathrooms: 7,
    garage: 2,
    yearBuilt: 2018,
    lat: 39.1911,
    lng: -106.8175,
    agentId: "a4",
    featured: false,
    tags: ["Luxury", "Mountain"],
    description: "A ski-in/ski-out chalet of exceptional quality, set amongst the pines of Aspen Mountain.",
    amenities: ["Ski Access", "Hot Tub", "Fireplace", "Sauna", "Home Theater", "Wine Room", "Heated Driveway"],
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    ],
    floorPlan: null,
    views: 3412,
    saves: 267,
    daysListed: 22,
    pendingApproval: false,
  },
  {
    id: "p7",
    title: "Austin Contemporary Home",
    address: "2205 West 10th Street, Austin, TX 78703",
    city: "Austin",
    state: "TX",
    zip: "78703",
    type: "House",
    status: "For Sale",
    price: 3450000,
    priceLabel: "$3,450,000",
    size: 4200,
    bedrooms: 4,
    bathrooms: 4,
    garage: 2,
    yearBuilt: 2023,
    lat: 30.2682,
    lng: -97.7636,
    agentId: "a2",
    featured: false,
    tags: ["New", "Modern"],
    description: "A strikingly contemporary home in one of Austin's most desirable neighbourhoods.",
    amenities: ["Pool", "Outdoor Kitchen", "Smart Home", "Home Office", "Gym"],
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800",
    ],
    floorPlan: null,
    views: 2187,
    saves: 189,
    daysListed: 9,
    pendingApproval: false,
  },
  {
    id: "p8",
    title: "Greenwich Estate",
    address: "55 Round Hill Road, Greenwich, CT 06830",
    city: "Greenwich",
    state: "CT",
    zip: "06830",
    type: "Estate",
    status: "For Sale",
    price: 16500000,
    priceLabel: "$16,500,000",
    size: 14000,
    bedrooms: 9,
    bathrooms: 12,
    garage: 6,
    yearBuilt: 1932,
    lat: 41.0534,
    lng: -73.6632,
    agentId: "a4",
    featured: false,
    tags: ["Historic", "Luxury", "Estate"],
    description: "A storied Georgian estate on 8.5 manicured acres in the prestigious Round Hill area.",
    amenities: ["Tennis Court", "Pool", "Guest House", "Carriage House", "Formal Gardens", "Wine Cellar", "Staff Quarters"],
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
    ],
    floorPlan: null,
    views: 4102,
    saves: 334,
    daysListed: 45,
    pendingApproval: false,
  },
  {
    id: "pp1",
    title: "Tribeca Loft",
    address: "12 N Moore Street, New York, NY 10013",
    city: "New York",
    state: "NY",
    zip: "10013",
    type: "Apartment",
    status: "Pending",
    price: 3200000,
    priceLabel: "$3,200,000",
    size: 2800,
    bedrooms: 3,
    bathrooms: 3,
    garage: 1,
    yearBuilt: 2018,
    lat: 40.7192,
    lng: -74.0073,
    agentId: "a2",
    featured: false,
    tags: ["Pending"],
    description: "Pending admin approval listing.",
    amenities: ["Gym", "Concierge"],
    images: ["https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800"],
    floorPlan: null,
    views: 110,
    saves: 8,
    daysListed: 1,
    pendingApproval: true,
  },
  {
    id: "pp2",
    title: "Hamptons Beach House",
    address: "200 Dune Road, Bridgehampton, NY 11932",
    city: "Bridgehampton",
    state: "NY",
    zip: "11932",
    type: "House",
    status: "Pending",
    price: 8500000,
    priceLabel: "$8,500,000",
    size: 6300,
    bedrooms: 6,
    bathrooms: 6,
    garage: 2,
    yearBuilt: 2020,
    lat: 40.9372,
    lng: -72.2997,
    agentId: "a1",
    featured: false,
    tags: ["Pending"],
    description: "Pending admin approval listing.",
    amenities: ["Beach Access", "Pool"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800"],
    floorPlan: null,
    views: 94,
    saves: 4,
    daysListed: 1,
    pendingApproval: true,
  },
  {
    id: "pp3",
    title: "Chelsea Penthouse",
    address: "555 W 23rd Street, New York, NY 10011",
    city: "New York",
    state: "NY",
    zip: "10011",
    type: "Penthouse",
    status: "Pending",
    price: 11000000,
    priceLabel: "$11,000,000",
    size: 5100,
    bedrooms: 4,
    bathrooms: 5,
    garage: 2,
    yearBuilt: 2024,
    lat: 40.7489,
    lng: -74.0047,
    agentId: "a3",
    featured: false,
    tags: ["Pending", "New"],
    description: "Pending admin approval listing.",
    amenities: ["Rooftop Terrace", "Private Elevator"],
    images: ["https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800"],
    floorPlan: null,
    views: 73,
    saves: 6,
    daysListed: 1,
    pendingApproval: true,
  },
];

const reviews = [
  {
    id: "r1",
    agentId: "a1",
    author: "Michael T.",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    rating: 5,
    date: "2024-01-15",
    text: "Sophia made our penthouse purchase seamless. Her knowledge of the Manhattan market is second to none.",
  },
  {
    id: "r2",
    agentId: "a1",
    author: "Priya S.",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    rating: 5,
    date: "2024-02-08",
    text: "Exceptional service from start to finish. Sophia was responsive and professional.",
  },
  {
    id: "r3",
    agentId: "a2",
    author: "David L.",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    rating: 5,
    date: "2024-01-28",
    text: "Marcus helped us identify an incredible investment opportunity.",
  },
  {
    id: "r4",
    agentId: "a3",
    author: "Sarah K.",
    avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    rating: 5,
    date: "2024-02-14",
    text: "Isabelle sold our Miami Beach home in 4 days above asking.",
  },
];

const appointments = [
  { id: "ap1", propertyId: "p1", agentId: "a1", clientName: "Alex Johnson", clientEmail: "alex@luxestate.com", date: "2026-04-24", time: "10:00 AM", status: "Confirmed", type: "Viewing" },
  { id: "ap2", propertyId: "p2", agentId: "a3", clientName: "Emma Williams", clientEmail: "emma@email.com", date: "2026-04-25", time: "2:30 PM", status: "Pending", type: "Viewing" },
  { id: "ap3", propertyId: "p4", agentId: "a3", clientName: "Robert Chang", clientEmail: "robert@email.com", date: "2026-04-26", time: "11:00 AM", status: "Confirmed", type: "Consultation" },
  { id: "ap4", propertyId: "p6", agentId: "a4", clientName: "Jennifer Davis", clientEmail: "jennifer@email.com", date: "2026-04-27", time: "3:00 PM", status: "Pending", type: "Viewing" },
];

const messages = [
  {
    id: "m1",
    agentId: "a1",
    fromName: "Emma Williams",
    fromEmail: "emma@email.com",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    subject: "Inquiry about Malibu Villa",
    preview: "Hi, I am very interested in scheduling a viewing...",
    body: "Hi, I am very interested in scheduling a viewing for Malibu Villa. Please let me know available slots.",
    time: "10:24 AM",
    unread: true,
  },
  {
    id: "m2",
    agentId: "a1",
    fromName: "Robert Chang",
    fromEmail: "robert@email.com",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
    subject: "Questions about Miami Mansion",
    preview: "Can you provide more details on the HOA fees?",
    body: "Can you provide more details on the HOA fees and property tax breakdown?",
    time: "Yesterday",
    unread: true,
  },
  {
    id: "m3",
    agentId: "a1",
    fromName: "Sarah Kim",
    fromEmail: "sarah@email.com",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    subject: "Re: Brooklyn Brownstone",
    preview: "Thank you for the information. We would like to proceed...",
    body: "Thank you for the information. We would like to proceed with next steps.",
    time: "Mon",
    unread: false,
  },
];

const users = [
  {
    id: "u1",
    name: "Alex Johnson",
    email: "user@luxestate.com",
    password: "demo123",
    role: "user",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "Active",
    savedProperties: ["p1", "p4"],
    compareList: [],
    notifications: [
      { id: "n1", type: "inquiry", message: "New inquiry on The Glass Penthouse", time: "5 min ago", read: false, createdAt: new Date() },
      { id: "n2", type: "appointment", message: "Viewing confirmed for Malibu Villa", time: "1 hr ago", read: false, createdAt: new Date(Date.now() - 3600000) },
      { id: "n3", type: "listing", message: "Your listing was approved", time: "3 hrs ago", read: true, createdAt: new Date(Date.now() - 10800000) },
      { id: "n4", type: "message", message: "Client message from Emma Williams", time: "Yesterday", read: true, createdAt: new Date(Date.now() - 86400000) },
    ],
  },
  {
    id: "u2",
    name: "Sophia Marlowe",
    email: "agent@luxestate.com",
    password: "demo123",
    role: "agent",
    agentId: "a1",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    status: "Active",
    savedProperties: [],
    compareList: [],
    notifications: [
      { id: "n5", type: "message", message: "You have 2 unread client messages", time: "15 min ago", read: false, createdAt: new Date() },
    ],
  },
  {
    id: "u3",
    name: "Admin User",
    email: "admin@luxestate.com",
    password: "demo123",
    role: "admin",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    status: "Active",
    savedProperties: [],
    compareList: [],
    notifications: [
      { id: "n6", type: "system", message: "3 listings pending approval", time: "30 min ago", read: false, createdAt: new Date() },
    ],
  },
  {
    id: "u4",
    name: "Emma Wilson",
    email: "emma@email.com",
    password: "demo123",
    role: "user",
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    status: "Active",
    savedProperties: [],
    compareList: [],
    notifications: [],
  },
  {
    id: "u5",
    name: "James Park",
    email: "james@email.com",
    password: "demo123",
    role: "user",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
    status: "Active",
    savedProperties: [],
    compareList: [],
    notifications: [],
  },
  {
    id: "u6",
    name: "Lisa Nguyen",
    email: "lisa@email.com",
    password: "demo123",
    role: "agent",
    agentId: "a2",
    avatar: "https://randomuser.me/api/portraits/women/52.jpg",
    status: "Active",
    savedProperties: [],
    compareList: [],
    notifications: [],
  },
  {
    id: "u7",
    name: "Tom Bradley",
    email: "tom@email.com",
    password: "demo123",
    role: "user",
    avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    status: "Suspended",
    savedProperties: [],
    compareList: [],
    notifications: [],
  },
];

module.exports = {
  agents,
  properties,
  reviews,
  appointments,
  messages,
  users,
};

